apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave-1
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: ctrl.srv.world
    path: "/var/nfs-data/pv02"
