---
apiVersion: v1
kind: Service
metadata:
  name: my-release-mysql
  labels:
    app: "mysql"
    component: "master"
    release: "my-release"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mysql"
    component: "master"
    release: "my-release"
